### ISSUE TITLE
Is it possible to use sax-wasm for dom manipulation?

### ISSUE THREAD

**Issue by toinbis** [justinwilaby/sax-wasm#19]
Hi,

wanted to inquire if sax-wasm is capable of manipulating the html file, not only parsing it?
What I need is a fast way to parse the html, select the element using selctor, replace the element with new one defined by me? tried kuchiki->wasm within Cloudflare workers environment, it's way to slow (at least the way I managed to make it work).

Thanks!

**Comment by justinwilaby** [comment]
@toinbis - sax-wasm can and is used as a means to replace blocks within an HTML file. Character positions and line numbers are provided with each event allowing you to find and replace values within the document. 

If the HTML is live and part of the DOM, the strategy changes because an xpath or selector must be created manually from the event hooks. This implementation is not provided out of the box but is certainly an interesting feature. I'll consider it for inclusion if you'll find it useful.
